# fly.toml app configuration file generated for comfyui-aida on 2024-12-16T15:20:28+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'comfyui-aida'
primary_region = 'ord'

[build]
  dockerfile = 'comfyui-flux-s3/Dockerfile'

[deploy]
  wait_timeout = '20m0s'

[[mounts]]
  source = 'workspace'
  destination = '/workspace'
  initial_size = '150gb'

[http_service]
  internal_port = 8188
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.http_options]
    idle_timeout = 300

  [[http_service.checks]]
    interval = '10m0s'
    timeout = '5m0s'
    grace_period = '10m0s'
    method = 'GET'
    path = '/'

[[vm]]
  size = 'l40s'
  cpu = 'performance-16x'
  memory = '128gb'
