# fly.toml app configuration file generated for comfyui-s3-sync on 2024-12-10T14:31:22+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'comfyui-s3-sync'
primary_region = 'ord'

[build]
  dockerfile = 'comfyui-flux-s3/Dockerfile'

[deploy]
  wait_timeout = '20m0s'

[[mounts]]
  source = 'workspace'
  destination = '/workspace'
  initial_size = '500gb'

[http_service]
  internal_port = 8188
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  [http_service.http_options]
    idle_timeout = 300

  [[http_service.checks]]
      grace_period = "10m"
      interval = "10m0s"
      method = "GET"
      path = "/"
      timeout = "5m"


[[vm]]
  size = 'l40s'
  cpu="performance-16x"
  memory = "128gb"